import { PropertyLead } from "../_components/property-listing-card"

export const mockListings: PropertyLead[] = [
  {
    id: 1,
    emirate: "Dubai",
    city: "Dubai",
    area: "Dubai Marina",
    propertyType: "Apartment",
    activityType: "rent_long",
    bedrooms: 2,
    bathrooms: 2,
    minSize: 1200,
    maxSize: 1500,
    minBudget: 120000,
    maxBudget: 150000,
    budgetFrequency: "Per Year",
    description: "Modern apartment with stunning marina views and high-end finishes",
    createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(), // 5 minutes ago
  },
  {
    id: 2,
    emirate: "Dubai",
    city: "Dubai",
    area: "Downtown Dubai",
    propertyType: "Apartment",
    activityType: "buy",
    bedrooms: 3,
    bathrooms: 3,
    minSize: 1800,
    maxSize: 2200,
    minBudget: 2500000,
    maxBudget: 3000000,
    budgetFrequency: "Per Year",
    description: "Luxury apartment with Burj Khalifa views, fully furnished",
    createdAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(), // 1 hour ago
  },
  {
    id: 3,
    emirate: "Dubai",
    city: "Dubai",
    area: "Palm Jumeirah",
    propertyType: "Villa",
    activityType: "rent_short",
    bedrooms: 4,
    bathrooms: 4,
    minSize: 3500,
    maxSize: 4000,
    minBudget: 25000,
    maxBudget: 35000,
    budgetFrequency: "Per Month",
    description: "Beachfront villa with private pool and garden",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(), // 2 hours ago
  },
  {
    id: 4,
    emirate: "Abu Dhabi",
    city: "Abu Dhabi",
    area: "Al Reem Island",
    propertyType: "Apartment",
    activityType: "rent_long",
    bedrooms: 1,
    bathrooms: 1,
    minSize: 800,
    maxSize: 900,
    minBudget: 75000,
    maxBudget: 85000,
    budgetFrequency: "Per Year",
    description: "Sea view studio with modern amenities",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(), // 4 hours ago
  },
  {
    id: 5,
    emirate: "Dubai",
    city: "Dubai",
    area: "Business Bay",
    propertyType: "Apartment",
    activityType: "buy",
    bedrooms: 2,
    bathrooms: 2,
    minSize: 1400,
    maxSize: 1600,
    minBudget: 1800000,
    maxBudget: 2000000,
    budgetFrequency: "Per Year",
    description: "Premium apartment with canal views",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(), // 8 hours ago
  },
  {
    id: 6,
    emirate: "Dubai",
    city: "Dubai",
    area: "Jumeirah Beach Residence",
    propertyType: "Apartment",
    activityType: "rent_short",
    bedrooms: 3,
    bathrooms: 3,
    minSize: 1600,
    maxSize: 1800,
    minBudget: 15000,
    maxBudget: 18000,
    budgetFrequency: "Per Month",
    description: "Beachfront apartment with full sea view",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(), // 12 hours ago
  },
  {
    id: 7,
    emirate: "Sharjah",
    city: "Sharjah",
    area: "Al Majaz",
    propertyType: "Apartment",
    activityType: "rent_long",
    bedrooms: 2,
    bathrooms: 2,
    minSize: 1100,
    maxSize: 1300,
    minBudget: 45000,
    maxBudget: 55000,
    budgetFrequency: "Per Year",
    description: "Waterfront apartment with city views",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(), // 1 day ago
  },
  {
    id: 8,
    emirate: "Dubai",
    city: "Dubai",
    area: "Arabian Ranches",
    propertyType: "Villa",
    activityType: "buy",
    bedrooms: 5,
    bathrooms: 5,
    minSize: 4200,
    maxSize: 4800,
    minBudget: 4500000,
    maxBudget: 5000000,
    budgetFrequency: "Per Year",
    description: "Luxury villa with golf course views",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(), // 2 days ago
  },
  {
    id: 9,
    emirate: "Abu Dhabi",
    city: "Abu Dhabi",
    area: "Yas Island",
    propertyType: "Apartment",
    activityType: "rent_short",
    bedrooms: 2,
    bathrooms: 2,
    minSize: 1300,
    maxSize: 1500,
    minBudget: 12000,
    maxBudget: 15000,
    budgetFrequency: "Per Month",
    description: "Modern apartment near Ferrari World",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(), // 3 days ago
  },
  {
    id: 10,
    emirate: "Dubai",
    city: "Dubai",
    area: "DIFC",
    propertyType: "Apartment",
    activityType: "rent_long",
    bedrooms: 1,
    bathrooms: 1,
    minSize: 950,
    maxSize: 1100,
    minBudget: 95000,
    maxBudget: 110000,
    budgetFrequency: "Per Year",
    description: "Premium studio in the heart of financial district",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(), // 4 days ago
  },
  {
    id: 11,
    emirate: "Dubai",
    city: "Dubai",
    area: "Dubai Hills Estate",
    propertyType: "Villa",
    activityType: "buy",
    bedrooms: 6,
    bathrooms: 7,
    minSize: 6000,
    maxSize: 7000,
    minBudget: 8500000,
    maxBudget: 9500000,
    budgetFrequency: "Per Year",
    description: "Luxury mansion with private garden and pool",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(), // 5 days ago
  },
  {
    id: 12,
    emirate: "Ajman",
    city: "Ajman",
    area: "Al Rashidiya",
    propertyType: "Apartment",
    activityType: "rent_long",
    bedrooms: 3,
    bathrooms: 2,
    minSize: 1500,
    maxSize: 1700,
    minBudget: 38000,
    maxBudget: 45000,
    budgetFrequency: "Per Year",
    description: "Spacious apartment with city views",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6).toISOString(), // 6 days ago
  },
] 